from prometheus_client import Counter, Gauge, Histogram, CollectorRegistry

REGISTRY = CollectorRegistry(auto_describe=True)

SPECTRUM_RECEIVED_TOTAL = Counter(
    'jade_spectrum_received_total',
    'Total spectrum data received',
    ['spectrum_type', 'device_id'],
    registry=REGISTRY,
)

DIFFUSION_SOLVED_TOTAL = Counter(
    'jade_diffusion_solved_total',
    'Total diffusion simulations completed',
    ['ion_type', 'solver_mode'],
    registry=REGISTRY,
)

DIFFUSION_DEPTH_MM = Gauge(
    'jade_diffusion_depth_mm',
    'Current diffusion penetration depth in mm',
    ['artifact_id', 'ion_type'],
    registry=REGISTRY,
)

ANOMALY_DETECTED_TOTAL = Counter(
    'jade_anomaly_detected_total',
    'Total anomaly detection runs',
    ['is_anomaly'],
    registry=REGISTRY,
)

ANOMALY_FORGERY_SCORE = Gauge(
    'jade_anomaly_forgery_score',
    'Current forgery probability score',
    ['artifact_id'],
    registry=REGISTRY,
)

ALERT_SENT_TOTAL = Counter(
    'jade_alert_sent_total',
    'Total alerts sent',
    ['alert_type', 'channel'],
    registry=REGISTRY,
)

WEBSOCKET_CONNECTIONS = Gauge(
    'jade_websocket_connections',
    'Current WebSocket connection count',
    ['consumer_type'],
    registry=REGISTRY,
)

SIMULATOR_SPECTRA_GENERATED = Counter(
    'jade_simulator_spectra_generated_total',
    'Total spectra generated by simulator',
    ['spectrum_type', 'is_forged'],
    registry=REGISTRY,
)

FORGERY_INJECTIONS_ACTIVE = Gauge(
    'jade_forgery_injections_active',
    'Number of active forgery injections',
    registry=REGISTRY,
)

CELERY_TASK_DURATION = Histogram(
    'jade_celery_task_duration_seconds',
    'Celery task execution duration',
    ['task_name'],
    buckets=[0.1, 0.5, 1.0, 5.0, 10.0, 30.0, 60.0, 300.0],
    registry=REGISTRY,
)
